name: C++ CI/CD Pipeline

# 워크플로우가 트리거되는 이벤트 정의
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # C++ 빌드 도구 설치
      - name: Install dependencies
        run: sudo apt-get install -y cmake g++ make

      # CMake 빌드 실행
      - name: Configure with CMake
        run: cmake -S . -B build

      - name: Build with Make
        run: cmake --build build

      # 빌드 후 테스트 실행
      - name: Run Tests
        run: ./build/MyCppProject
